name: uphome_app
description: "Application to find the house you have always wanted "
publish_to: 'none'

version: 0.0.2+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  flutter_riverpod: ^2.6.1
  dio: ^5.7.0
  path: ^1.9.0
  flutter_blue: ^0.8.0
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
  - assets/db/database.db
